### ISSUE TITLE
Unable to access X.509 client certificates

### ISSUE THREAD

**Issue by ctron** [ntex-rs/examples#11]
Before the most recent version change, it was possible to access the underlying transport, and extract the X.509 client certificates from it.

Now, there is is `Io<Sealed>` type, which is also used by the `IoBoxed` type (which is being used by the Mqtt implementation). However, there seems to be no way to get access to the certificates.

The way to acquire them differs between `rustls` and `openssl`, so previously we had a trait to abstract this, and added the trait to all requirements of the `Io` type parameter.

I guess the new way would be to implement a `Filter::query` method to retrieve the certificates. And the `TlsServerFilter` should provide an implementation which returns them.

**Comment by ctron** [comment]
Sorry, I guess that issue should have gone to the `ntex` repository, rather the examples.

I also did find out that this seems to be supported, the way described, using `openssl`. As I am using `rustls` the situation is a bit different.

**Comment by fafhrd91** [comment]
rustls support is added
