### ISSUE TITLE
ntex-files not found

### ISSUE THREAD

**Issue by vasily-kartashov** [ntex-rs/examples#6]
In https://github.com/ntex-rs/examples/tree/master/basics you reference crate "ntex-files" which I cannot find under https://github.com/rust-lang/crates.io-index/tree/master/nt/ex

```
stdout :     Updating crates.io index
error: no matching package named `ntex-files` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
```

Is it work in progress? If so, is there an alternative example how to serve a binary file?

**Comment by fafhrd91** [comment]
it should work within examples workspace. actual package is nit released and is part od ntex-extra repo

**Comment by vasily-kartashov** [comment]
Thank you! It compiles fine after I've added

```
[patch.crates-io]
ntex-files = { git = "https://github.com/ntex-rs/ntex-extras.git" }
``` 

to `Cargo.toml`
