### ISSUE TITLE
Setting Access-Control-Allow-Origin: * for all resources

### ISSUE THREAD

**Issue by vasily-kartashov** [ntex-rs/examples#8]
Is there a way to set the header `Access-Control-Allow-Origin: *` for all resources, without going `with_header` on each and every one of them?

**Comment by fafhrd91** [comment]
you can use ntex-cors if you need cars support or DefaultHeader middleware

**Comment by vasily-kartashov** [comment]
@fafhrd91 It seems that `ntex-cors` only supports `ntex: 0.1`, but I also use `ntex-files` with requires `ntex: 0.3`. Is there a way to avoid / resolve conflict?

**Comment by fafhrd91** [comment]
cors from master supports 0.3
